export const dashboard = <i className="fa-solid fa-house"></i>
export const transactions = <i className="fa-solid fa-credit-card"></i>
export const expenses = <i className="fa-solid fa-money-bill-transfer"></i>
export const trend = <i className="fa-solid fa-money-bill-trend-up"></i>
export const signout = <i className="fa-solid fa-right-from-bracket"></i>
export const plus = <i className="fa-solid fa-plus"></i>
export const dollar = <i className="fa-solid fa-dollar-sign"></i>
export const calendar = <i className="fa-regular fa-calendar"></i>
export const comment = <i className="fa-regular fa-comment"></i>
export const trash = <i className="fa-solid fa-trash"></i>