export const dashboard = <i className="fa-solid fa-house"></i>
export const transactions = <i className="fa-solid fa-credit-card"></i>
export const expenses = <i className="fa-solid fa-money-bill-transfer"></i>
export const trend = <i className="fa-solid fa-money-bill-trend-up"></i>
export const signout = <i className="fa-solid fa-right-from-bracket"></i>
export const plus = <i className="fa-solid fa-plus"></i>
export const dollar = <i className="fa-solid fa-dollar-sign"></i>
export const calendar = <i className="fa-regular fa-calendar"></i>
export const comment = <i className="fa-regular fa-comment"></i>
export const trash = <i className="fa-solid fa-trash"></i>
export const money = <i className="fa-solid fa-money-check"></i>
export const freelance = <i className="fa-solid fa-code"></i>
export const stocks = <i className="fa-solid fa-arrow-trend-up"></i>
export const investments = <i className="fa-solid fa-business-time"></i>
export const crypto = <i className="fa-solid fa-bitcoin-sign"></i>
export const pension = <i className="fa-solid fa-landmark"></i>
export const other = <i className="fa-solid fa-ellipsis"></i>
export const car = <i className="fa-solid fa-car"></i>
export const food = <i className="fa-solid fa-utensils"></i>
export const healthcare = <i className="fa-solid fa-notes-medical"></i>
export const subscriptions = <i className="fa-solid fa-tv"></i>
export const clothing = <i classname="fa-solid fa-shirt"></i>
export const education = <i className="fa-solid fa-school"></i>